name: Docker CI

on:
  push:
    branches:
      - 'main'
  schedule:
    - cron: '28 3 * * 0' #Sundays at 3:28 AM
    
defaults:
  run:
    working-directory: ./docker/  # docker/build-push-action@v2 is not applying a working-directory
    
jobs:
  docker:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repo
        uses: actions/checkout@v2
      
      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v1

      - name: Login to DockerHub
        uses: docker/login-action@v1
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}

      - name: Build and push
        id: docker_build
        uses: docker/build-push-action@v2
        with:
          context: ./docker/
          push: true
          tags: arburk/codeql-analyzer-java:latest
