name: Release

on: 
  push:
    tags:
      - 'v*' # Push events to matching v*, i.e. v1.0, v20.15.10
  workflow_run:
    workflows: [ "Prepare Release" ]
    types:
      - completed

jobs:
  build:

    runs-on: ubuntu-latest
    permissions:
      contents: write
      packages: write
      deployments: write
      
    steps:
      - name: Checkout
        uses: actions/checkout@v2

      - name: Deploy to Github Package Registry
        env:
          GITHUB_USERNAME: x-access-token
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        run: mvn -B --settings .github/maven-settings.xml deploy
        
      - name: Release using Github CLI
        run: gh release create ${GITHUB_REF##*/} ./target/*.jar -t "Release ${GITHUB_REF##*/}"
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
