name: Prepare Release

on:
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@latest

      - name: Prepare release with Maven
        run: mvn -B release:prepare