name: update codeql-cli-binaries version
on: 
  workflow_dispatch:
    inputs:
      old_version:
        description: 'specify version to be replaced/searched for (e.g. v2.20.3)'
        required: true
        type: string
      new_version:
        description: 'specify new version to be set (e.g. v2.20.4)'
        required: true
        type: string
        
## If using the repository's GITHUB_TOKEN and your repository was created after 2nd February 2023, the default permission is read-only. 
## Elevate the permissions in this workflow.
permissions: 
  contents: write
  pull-requests: write

jobs:
  build:
    runs-on: ubuntu-latest
    permissions:
      contents: write
    steps:
      - name: Checkout Repository
        uses: actions/checkout@v4

      - name: Find and Replace
        uses: jacobtomlinson/gha-find-replace@v3
        with:
          find: ${{ inputs.old_version }} 
          replace: ${{ inputs.new_version }} 
          include: "docker/**"
          regex: false
          
      - name: Create Pull Request
        id: cpr
        uses: peter-evans/create-pull-request@271a8d0340265f705b14b6d32b9829c1cb33d45e
        with:
          token: ${{ secrets.GITHUB_TOKEN }}
          branch: 'codeql-cli-${{ inputs.new_version }}'
          base: main
          commit-message: 'build: bump cql from ${{ inputs.old_version }} to ${{ inputs.new_version }}'
          title: 'Update CodeQL to version ${{ inputs.new_version }}'
          body: Bump cql from ${{ inputs.old_version }} to ${{ inputs.new_version }}
          labels: automated_pr
          maintainer-can-modify: false
